/* ============================================================
   Pulse — AI Weekly Pipeline Digest  (Feature 6)
   On-demand Monday-morning briefing: what moved last week,
   what's gone cold, overdue follow-ups, and top 3 priorities
   for the coming week — all generated by AI from live data.
   ============================================================ */

async function openWeeklyDigestModal() {
  openModal('📋 Weekly Pipeline Digest', `
    <div class="p-6">
      <div id="wd-loading" class="flex flex-col items-center gap-3 py-10 justify-center">
        <svg class="animate-spin w-6 h-6 text-brand-500" fill="none" viewBox="0 0 24 24">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/>
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"/>
        </svg>
        <span class="text-sm text-surface-500" id="wd-loading-text">Pulling pipeline data…</span>
      </div>
      <div id="wd-content" class="hidden"></div>
    </div>
  `, [
    { label: 'Close', onclick: 'closeModal()', class: 'btn-secondary' },
    { label: '↺ Regenerate', onclick: '_regenerateWeeklyDigest()', class: 'btn-secondary', id: 'wd-regen-btn' },
  ]);

  await _buildWeeklyDigest();
}

async function _regenerateWeeklyDigest() {
  const contentEl = document.getElementById('wd-content');
  const loadEl    = document.getElementById('wd-loading');
  if (contentEl) contentEl.classList.add('hidden');
  if (loadEl)    loadEl.classList.remove('hidden');
  await _buildWeeklyDigest();
}

async function _buildWeeklyDigest() {
  const loadEl    = document.getElementById('wd-loading');
  const loadText  = document.getElementById('wd-loading-text');
  const contentEl = document.getElementById('wd-content');
  const regenBtn  = document.getElementById('wd-regen-btn');
  if (regenBtn) regenBtn.disabled = true;

  try {
    const now        = new Date();
    const oneWeekAgo = new Date(now - 7 * 86400000);
    const today      = now.toISOString().split('T')[0];

    // ── Gather all data ──────────────────────────────────────────────────────
    if (loadText) loadText.textContent = 'Gathering pipeline data…';
    const [deals, allTasks, calls, history] = await Promise.all([
      DB.getAll(STORES.deals),
      DB.getAll(STORES.dealTasks),
      DB.getAll(STORES.calls),
      DB.getAll(STORES.dealHistory),
    ]);

    const uid          = currentUser.id;
    const myDeals      = deals.filter(d => d.userId === uid);
    const activeDeals  = myDeals.filter(d => !['Closed - Won','Closed - Lost','Rejected'].includes(d.stage));
    const myTasks      = allTasks.filter(t => t.userId === uid);
    const myCalls      = calls.filter(c => c.userId === uid);
    const myHistory    = history.filter(h => h.userId === uid);

    // What moved last week (stage changes in history)
    const recentHistory = myHistory.filter(h => new Date(h.timestamp || h.createdAt) >= oneWeekAgo);
    const stageChanges  = recentHistory.filter(h => h.type === 'stage_change');
    const recentCalls   = myCalls.filter(c => c.date && new Date(c.date) >= oneWeekAgo);

    // Overdue tasks
    const overdueTasks = myTasks.filter(t =>
      t.status !== 'done' && t.dueDate && new Date(t.dueDate) < now
    );

    // Cold deals (no activity in >21 days)
    const coldDeals = activeDeals.filter(d => {
      const lastAct = d.updatedAt || d.createdAt;
      return lastAct && (now - new Date(lastAct)) / 86400000 > 21;
    });

    // Hot deals (advanced stages)
    const hotDeals = activeDeals.filter(d =>
      ['LOI Drafted','LOI Submitted','Due Diligence','Exclusivity','Legal / Closing'].includes(d.stage)
    );

    // ── Build AI prompt ──────────────────────────────────────────────────────
    if (loadText) loadText.textContent = 'Writing your digest…';

    const stageChangeLines = stageChanges.slice(0, 8).map(h => {
      const d = myDeals.find(x => x.id === h.dealId);
      return d ? `• "${d.name}" moved to ${h.newStage || h.data?.stage || '?'}` : '';
    }).filter(Boolean).join('\n') || 'No stage changes recorded';

    const callLines = recentCalls.slice(0, 6).map(c => {
      const d = myDeals.find(x => x.id === c.dealId);
      return d ? `• Call with ${d.name}: ${(c.summary || c.notes || '').slice(0, 80)}` : `• ${c.contactName || 'contact'}: ${(c.summary || '').slice(0, 80)}`;
    }).filter(Boolean).join('\n') || 'No calls logged';

    const overdueLines = overdueTasks.slice(0, 8).map(t => {
      const d = myDeals.find(x => x.id === t.dealId);
      const daysOverdue = Math.floor((now - new Date(t.dueDate)) / 86400000);
      return `• [${d?.name || 'deal'}] ${t.title} — ${daysOverdue}d overdue`;
    }).join('\n') || 'None';

    const hotLines = hotDeals.map(d =>
      `• ${d.name} (${d.stage}) — Rev: ${d.revenue ? '$' + d.revenue.toLocaleString() : '?'}, EBITDA: ${d.ebitda ? '$' + d.ebitda.toLocaleString() : '?'}`
    ).join('\n') || 'None at advanced stage';

    const coldLines = coldDeals.slice(0, 5).map(d => {
      const daysIdle = Math.floor((now - new Date(d.updatedAt || d.createdAt)) / 86400000);
      return `• ${d.name} (${d.stage}) — idle for ${daysIdle} days`;
    }).join('\n') || 'All deals have recent activity';

    const allOpenTasks = myTasks.filter(t => t.status !== 'done').length;

    const systemPrompt = `You are a search fund advisor writing a crisp Monday-morning pipeline digest.
Write in second person ("you have", "your pipeline"). Be specific, direct, and actionable.
No fluff, no lengthy preambles. Format with clear sections using ## headers.`;

    const userPrompt = `Write a weekly pipeline digest for this search fund as of ${today}.

PIPELINE SNAPSHOT:
- Active deals: ${activeDeals.length}
- Hot deals (LOI stage+): ${hotDeals.length}
- Cold deals (>21d idle): ${coldDeals.length}
- Open tasks: ${allOpenTasks} (${overdueTasks.length} overdue)

WHAT MOVED LAST WEEK (stage changes):
${stageChangeLines}

CALLS LOGGED LAST WEEK:
${callLines}

HOT DEALS RIGHT NOW:
${hotLines}

COLD DEALS NEEDING ATTENTION:
${coldLines}

OVERDUE TASKS:
${overdueLines}

Write a concise digest with these sections:
## What Happened This Week
## What's Hot Right Now
## What's Gone Cold
## Overdue & Needs Attention
## Your Top 3 Priorities This Week

For the Top 3 Priorities, be very specific — name the deal and the exact action.`;

    const digest = await callAI(systemPrompt, userPrompt, 900, 0.3);

    // ── Render ───────────────────────────────────────────────────────────────
    if (loadEl) loadEl.classList.add('hidden');
    if (!contentEl) return;

    const html = digest
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/^## (.+)$/gm, '<h3 class="font-semibold text-surface-800 dark:text-surface-200 text-sm mt-5 mb-2 pb-1 border-b border-surface-100 dark:border-surface-800">$1</h3>')
      .replace(/^[-•*]\s+(.+)$/gm, '<li class="ml-4 list-disc text-sm text-surface-600 dark:text-surface-400 mb-1">$1</li>')
      .replace(/\n\n/g, '<br/>');

    const dateStr = now.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });

    contentEl.innerHTML = `
      <div class="flex items-center justify-between mb-4">
        <div>
          <p class="text-xs text-surface-400">${dateStr}</p>
          <div class="flex gap-3 mt-1">
            <span class="text-xs font-medium text-brand-600">${activeDeals.length} active deals</span>
            <span class="text-xs font-medium text-red-500">${overdueTasks.length} overdue tasks</span>
            <span class="text-xs font-medium text-yellow-600">${coldDeals.length} cold deals</span>
          </div>
        </div>
        <button onclick="navigator.clipboard.writeText(${JSON.stringify(digest)}).then(() => showToast('Copied!','success'))"
                class="btn-secondary btn-sm text-xs">Copy</button>
      </div>
      <div class="prose prose-sm dark:prose-invert max-w-none leading-relaxed">${html}</div>
    `;
    contentEl.classList.remove('hidden');

  } catch (err) {
    if (loadEl) loadEl.innerHTML = `<p class="text-sm text-red-500 text-center">${escapeHtml(err.message)}</p>`;
  }

  if (regenBtn) regenBtn.disabled = false;
}
